import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Header from "../components/Header";
import HomeLayout from "../components/HomeLayout";
import LatestPost from "../components/LatestPost";
import NewsLetter from "../components/NewsLetter";
import SecondLatest from "../components/SecondLatest";
import FeaturedPosts from "../components/FeaturedPosts";
import PostHighlight from "../components/PostHighlight";
import Footer from "../components/Footer";



const tags = ["Idea", "Interior", "Lifestyle", "Design", "Health", "Eco", "Review"];

const Home: NextPage = ({ myposts }: any) => {
  return (
    <div>
      <Head>
        <title>Home | Now Whats That</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeLayout >
        <h1 className="text-center md:text-6xl text-2xl md:w-4/6 w-full mt-20 font-dancing-script font-medium leading-relaxed">
          <span className="font-bold">Hey, I’m Wajahat.</span> I promote positive culture through <span className="font-bold">inspiring articles</span> on health, design, and web.
        </h1>
        {/* Search */}
        <div className="flex items-center rounded-full px-6 py-5 bg-green-100 md:w-4/12 w-10/12 justify-between my-10">
          <input type="text" placeholder="Search posts , tags and authors"
            className="outline-none bg-green-100 border-none w-3/4 md:text-md text-sm tracking-wider" />
          <Image src="/assets/images/search.png" alt="search" width="20" height="30" />
        </div>
        {/* Tags Container */}
        <div className="w-full"><h3 className="uppercase my-2 font-thin text-sm lg:ml-0 ml-4">Popular Tags</h3></div>
        <div className="flex items-center w-full md:justify-between flex-wrap justify-evenly">
          {tags.map((tag: string, index: number) => {
            return <div key={index} className="relative cursor-pointer my-2 transition-all hover:-translate-y-1">
              <Image src={`/assets/tags/tag (${index + 1}).jpeg`} alt="tag-img" width="100" height="100"
                className="w-44 h-32 object-cover rounded-md" />
              <p className="absolute bottom-0 bg-slate-100 p-1 px-3 font-semibold m-2 rounded-full text-sm text-gray-500">{tag}</p>
            </div>
          })}
        </div>
        <div className="my-6"></div>
        {/* Whats New Container */}
        <div className="w-full"><h3 className="uppercase my-2 font-thin text-sm lg:ml-0 ml-4">What’s new</h3></div>
        <div className="flex w-full md:flex-row flex-col">
          <div className="md:w-3/4 w-full">
            <LatestPost />
          </div>
          <div className="md:w-1/4 w-full flex flex-col items-center">
            <NewsLetter />
            <SecondLatest />
            <SecondLatest />
          </div>
        </div>
        <div className="w-full"><h3 className="uppercase my-2 mt-16 font-thin text-sm lg:ml-0 ml-4">Featured posts</h3></div>
        <FeaturedPosts />
        <div className="w-full"><h3 className="uppercase mt-14 font-thin text-sm lg:ml-0 ml-4">All posts</h3></div>
        {/* All posts container */}
        <div className="flex flex-wrap w-full">
          <PostHighlight />
          <PostHighlight />
          <PostHighlight />
          <PostHighlight />
          <PostHighlight />
        </div>
        <div className="flex justify-center w-full my-6">
          <Link href="/" className="text-white bg-green-800 px-6 py-3 rounded-full transition-all duration-300 hover:px-8">See more</Link>
        </div>
        <Footer />
      </HomeLayout>
    </div>
  );
};

export default Home;
